//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InfraRecorder.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PROPPAGE_DEVICEGENERAL      106
#define IDR_MAINFRAME                   128
#define ID_VIEW_UPLEVEL                 129
#define ID_TRACK_READ                   130
#define ID_TRACK_VERIFY                 131
#define ID_TRACK_ERASE                  132
#define ID_SHELLEXT_ADD                 133
#define ID_SHELLEXT_REMOVE              134
#define ID_SHELL_PASTE                  135
#define ID_BOOT_ADD                     135
#define ID_BOOT_REMOVE                  136
#define ID_BOOT_EDIT                    137
#define IDR_MAINFRAME_PORTABLE          138
#define ID_NEWPROJECT_DATA              138
#define IDD_PROGRESSDLG                 201
#define IDD_SIMPLEPROGRESSDLG           202
#define IDD_ERASEDLG                    203
#define IDB_SPLASHBITMAP                204
#define IDD_LOGDLG                      205
#define IDD_DEVICESDLG                  206
#define IDD_PROPPAGE_DEVICEADVANCED     207
#define IDD_PROPPAGE_BURNIMAGEGENERAL   208
#define IDD_PROPPAGE_BURNIMAGEADVANCED  209
#define IDD_WAITDLG                     210
#define IDI_MIXEDICON                   211
#define IDD_PROPPAGE_PROJECTPROPGENERAL 211
#define IDI_AUDIOICON                   212
#define IDD_PROPPAGE_PROJECTPROPISO     212
#define IDI_DATAICON                    213
#define IDD_PROPPAGE_PROJECTPROPFIELDS  213
#define IDI_DVDVIDEOICON                214
#define IDR_PROJLISTSELMENU             214
#define IDD_PROPPAGE_PROJECTPROPAUDIO   214
#define IDR_PROJLISTNOSELMENU           215
#define IDB_MINITOOLBARBITMAP           216
#define IDB_MINITOOLBARBITMAP_          217
#define IDD_EDITTRACKDLG                218
#define IDD_FIXATEDLG                   219
#define IDD_TRACKSDLG                   220
#define IDD_PROPPAGE_CONFIGGENERAL      221
#define IDD_PROPPAGE_CONFIGADVANCED     222
#define IDB_TRACKTOOLBARBITMAP          223
#define IDD_PROPPAGE_CONFIGLANGUAGE     223
#define IDB_TRACKTOOLBARBITMAP_         224
#define IDD_PROPPAGE_CONFIGSHELLEXT     224
#define IDD_NEWFILEEXTDLG               225
#define IDD_PROPPAGE_COPYDISCGENERAL    226
#define IDB_MAINSMALLBITMAP             228
#define IDB_MAINSMALLBITMAP_            229
#define IDD_INFODLG                     231
#define IDD_PROPPAGE_DISCGENERAL        232
#define IDD_IMPORTSESSIONDLG            233
#define IDB_SPLASHBITMAP_               234
#define IDI_PROJECTICON                 238
#define IDD_SAVETRACKSDLG               239
#define IDD_PROPPAGE_READOPTIONS        240
#define IDD_PROPPAGE_COPYIMAGEGENERAL   241
#define IDD_PROPPAGE_PROJECTPROPBOOT    242
#define IDD_ADDBOOTIMAGEDLG             243
#define IDR_DIAGNOSTICSMENU             244
#define IDD_DRIVELETTERDLG              245
#define IDI_REFRESHICON                 247
#define IDD_CONFIRMFILEREPLACEDLG       248
#define IDB_MAINLARGEBITMAP             249
#define IDD_PROPPAGE_PROJECTPROPFILESYS 249
#define IDB_MAINLARGEBITMAP_            250
#define IDD_PROPPAGE_PROJECTPROPUDF     250
#define IDB_PANECLOSEBITMAP             251
#define IDB_BITMAP1                     275
#define IDB_LOGOSMALLBITMAP             277
#define IDR_WELCOMELOGOPNG              278
#define IDR_BUTTONFPNG                  279
#define IDR_BUTTONHPNG                  280
#define IDR_BUTTONHFPNG                 281
#define IDR_BUTTONNPNG                  282
#define IDR_MBUTTONFPNG                 283
#define IDR_MBUTTONHPNG                 284
#define IDR_MBUTTONHFPNG                285
#define IDR_MBUTTONHFS1PNG              286
#define IDR_MBUTTONHFS2PNG              287
#define IDR_MBUTTONHS1PNG               288
#define IDR_MBUTTONHS2PNG               289
#define IDR_MBUTTONNPNG                 290
#define IDR_WIZARDAUDIOPNG              291
#define IDR_WIZARDCOPYPNG               292
#define IDR_WIZARDDATAPNG               293
#define IDR_WIZARDREADPNG               294
#define IDR_WIZARDVIDEOPNG              295
#define IDR_WIZARDWRITEPNG              296
#define IDC_TOTALPROGRESS               1000
#define IDC_TOTALSTATIC                 1001
#define IDC_MESSAGELIST                 1004
#define IDC_MESSAGESTATIC               1005
#define IDC_STATUSSTATIC                1005
#define IDC_BEVELSTATIC                 1006
#define IDC_DEVICESTATIC                1007
#define IDC_BEVELSTATIC2                1007
#define IDC_BUFFERSTATIC                1008
#define IDC_BEVELSTATIC4                1008
#define IDC_BUFFERPROGRESS              1009
#define IDC_BEVELSTATIC3                1009
#define IDC_BEVELSTATIC5                1009
#define IDC_RECORDERSTATIC              1010
#define IDC_RECORDERCOMBO               1011
#define IDC_METHODSTATIC                1012
#define IDC_METHODCOMBO                 1013
#define IDC_FORCECHECK                  1014
#define IDC_EJECTCHECK                  1015
#define IDC_SIMULATECHECK               1016
#define IDC_LOGEDIT                     1017
#define IDC_BUTTON1                     1018
#define IDC_RESCANBUTTON                1018
#define IDC_RELOADBUTTON                1018
#define IDC_BROWSEBUTTON                1018
#define IDC_DIAGNOSTICSBUTTON           1018
#define IDC_YESALLBUTTON                1018
#define IDC_WEBSITEBUTTON               1018
#define ID_SAVEASBUTTON                 1019
#define IDC_DEVICELIST                  1020
#define IDC_INFOSTATIC                  1021
#define IDC_ICONSTATIC                  1022
#define IDC_NAMESTATIC                  1023
#define IDC_OLDICONSTATIC               1023
#define IDC_TYPELABELSTATIC             1024
#define IDC_NEWICONSTATIC               1024
#define IDC_LOCATIONLABELSTATIC         1025
#define IDC_TYPESTATIC                  1026
#define IDC_LOCATIONSTATIC              1027
#define IDC_BUFFERLABELSTATIC           1028
#define IDC_MAXREADLABELSTATIC          1029
#define IDC_MAXREADSTATIC               1030
#define IDC_MAXWRITELABELSTATIC         1031
#define IDC_MAXWRITESTATIC              1032
#define IDC_READSTATIC                  1033
#define IDC_READCDRCHECK                1034
#define IDC_READDVDRAMCHECK             1035
#define IDC_READCDRWCHECK               1036
#define IDC_READDVDROMCHECK             1037
#define IDC_READDVDRCHECK               1038
#define IDC_WRITESTATIC                 1039
#define IDC_WRITECDRCHECK               1040
#define IDC_WRITECDRWCHECK              1041
#define IDC_WRITEDVDRCHECK              1042
#define IDC_WRITEDVDRAMCHECK            1043
#define IDC_ADVLIST                     1044
#define IDC_WRITESPEEDSTATIC            1046
#define IDC_WRITESPEEDCOMBO             1047
#define IDC_WRITEMETHODSTATIC           1048
#define IDC_WRITEMETHODCOMBO            1049
#define IDC_BUPCHECK                    1052
#define IDC_PADCHECK                    1053
#define IDC_FIXATECHECK                 1054
#define IDC_OVERBURNCHECK               1055
#define IDC_SWABCHECK                   1056
#define IDC_IGNORESIZECHECK             1057
#define IDC_IMMEDCHECK                  1058
#define IDC_AUDIOMASTERCHECK            1059
#define IDC_FORCESPEEDCHECK             1060
#define IDC_VARIRECCHECK                1061
#define IDC_VARIRECSLIDER               1062
#define IDC_VARIRECEDIT                 1063
#define IDC_AUTOSCANCHECK               1064
#define IDC_NAMEEDIT                    1065
#define IDC_SIZELABELSTATIC             1066
#define IDC_CONTAINSLABELSTATIC         1067
#define IDC_SIZESTATIC                  1068
#define IDC_CONTAINSSTATIC              1069
#define IDC_LEVELSTATIC                 1070
#define IDC_LEVELCOMBO                  1071
#define IDC_JOLIETCHECK                 1074
#define IDC_JOLIETLONGNAMESCHECK        1075
#define IDC_PUBLISHEREDIT               1076
#define IDC_PUBLISHERSTATIC             1077
#define IDC_PREPAREREDIT                1078
#define IDC_SYSTEMEDIT                  1079
#define IDC_VOLUMEEDIT                  1080
#define IDC_PREPARERSTATIC              1081
#define IDC_SYSTEMSTATIC                1082
#define IDC_VOLUMESTATIC                1083
#define IDC_COPYRIGHTSTATIC             1084
#define IDC_COPYRIGHTEDIT               1085
#define IDC_ABSTRACTEDIT                1086
#define IDC_BIBLIOGRAPHICEDIT           1087
#define IDC_ABSTRACTSTATIC              1088
#define IDC_BIBLIOGRAPHICSTATIC         1089
#define IDC_FORMATCOMBO                 1092
#define IDC_FORMATSTATIC                1093
#define IDC_ALBUMSTATIC                 1094
#define IDC_ALBUMEDIT                   1095
#define IDC_ARTISTEDIT                  1096
#define IDC_ARTISTSTATIC                1097
#define IDC_TRACKLIST                   1098
#define IDC_TITLESTATIC                 1099
#define IDC_TITLEEDIT                   1100
#define IDC_DEVICECOMBO                 1103
#define IDC_DRIVESTATIC                 1104
#define IDC_AUTORUNCHECK                1105
#define IDC_LOGCHECK                    1106
#define IDC_TRACKCOMBO                  1106
#define IDC_LANGUAGESTATIC              1107
#define IDC_LANGUAGECOMBO               1108
#define IDC_LANGUAGEINFOSTATIC          1109
#define IDC_SHELLEXTCHECK               1110
#define IDC_SHELLEXTSUBMENUCHECK        1111
#define IDC_SHELLEXTTEXTSTATIC          1112
#define IDC_SHELLEXTICONCHECK           1113
#define IDC_SHELLEXTLIST                1114
#define IDC_DESCSTATIC                  1115
#define IDC_DESCEDIT                    1116
#define IDC_EXTSTATIC                   1117
#define IDC_EXTEDIT                     1118
#define IDC_SOURCECOMBO                 1119
#define IDC_SOURCESTATIC                1120
#define IDC_COMBO2                      1121
#define IDC_TARGETCOMBO                 1121
#define IDC_TARGETSTATIC                1122
#define IDC_IMAGESTATIC                 1127
#define IDC_IMAGEEDIT                   1128
#define IDC_ONFLYCHECK                  1129
#define IDC_ONFLYSTATIC                 1130
#define IDC_REMEMBERSHELLCHECK          1131
#define IDC_SHELLFOLDERGROUPSTATIC      1134
#define IDC_SHELLFOLDERINFOSTATIC       1135
#define IDC_SHELLFOLDEREDIT             1136
#define IDC_SHELLFOLDERBROWSEBUTTON     1137
#define IDC_DISPLAYMSGCHECK             1138
#define IDC_SHELLFOLDERBROWSEBUTTON2    1138
#define IDC_TEMPFOLDERBROWSEBUTTON      1138
#define IDC_BOOKLABELSTATIC             1139
#define IDC_BOOKSTATIC                  1140
#define IDC_REGIONLABELSTATIC           1141
#define IDC_REGIONSTATIC                1142
#define IDC_LAYERLABELSTATIC            1143
#define IDC_LAYERSTATIC                 1144
#define IDC_TRACKSTATIC                 1145
#define IDC_TRACKLABELSTATIC            1146
#define IDC_SESSIONSTATIC               1147
#define IDC_SESSIONLABELSTATIC          1148
#define IDC_STATUSLABELSTATIC           1149
#define IDC_USEDSPACESTATIC             1150
#define IDC_USEDSPACELABELSTATIC        1151
#define IDC_FREESPACESTATIC             1152
#define IDC_FREESPACELABELSTATIC        1153
#define IDC_LOGOSTATIC                  1154
#define IDC_WHITESTATIC                 1155
#define IDC_HELPBUTTON                  1157
#define IDC_VERSIONSTATIC               1160
#define IDC_ASSOCIATECHECK              1161
#define IDC_CLONECHECK                  1161
#define IDC_NOREADERRCHECK              1161
#define IDC_TEMPFOLDERGROUPSTATIC       1162
#define IDC_TEMPFOLDERINFOSTATIC        1163
#define IDC_TEMPFOLDEREDIT              1164
#define IDC_TARGETEDIT                  1165
#define IDC_AUDIOFORMATSTATIC           1166
#define IDC_AUDIOFORMATCOMBO            1167
#define IDC_AUDIOFORMATBUTTON           1168
#define IDC_CODECSSTATIC                1169
#define IDC_CODECLIST                   1170
#define IDC_FIFOGROUPSTATIC             1171
#define IDC_FIFOINFOSTATIC              1172
#define IDC_FIFOEDIT                    1173
#define IDC_FIFOMBSTATIC                1174
#define IDC_NOREADCORRCHECK             1175
#define IDC_SUBCHANNELCHECK             1176
#define IDC_READSUBCHANNELCHECK         1176
#define IDC_READSPEEDSTATIC             1177
#define IDC_READSPEEDCOMBO              1178
#define IDC_SPIN1                       1179
#define IDC_WRITESPEEDSPIN              1179
#define IDC_BOOTSTATIC                  1180
#define IDC_LIST                        1181
#define IDC_BOOTCATALOGEDIT             1182
#define IDC_BOOTCATALOGSTATIC           1183
#define IDC_EMULATIONSTATIC             1185
#define IDC_EMULATIONCOMBO              1186
#define IDC_OPTIONSSTATIC               1187
#define IDC_NOBOOTCHECK                 1188
#define IDC_BOOTINFOTABLECHECK          1189
#define IDC_BOOTSEGMENTEDIT             1190
#define IDC_BOOTSEGMENTSTATIC           1191
#define IDC_BOOTSIZEEDIT                1192
#define IDC_BOOTSIZESTATIC              1193
#define IDC_CHECK2                      1196
#define IDC_CHECK                       1196
#define IDC_OMITVNCHECK                 1196
#define IDC_CHECK1                      1197
#define IDC_VERIFYCHECK                 1197
#define IDC_SMOKECHECK                  1197
#define IDC_DEEPDIRCHECK                1197
#define IDC_DRIVELETTERCOMBO            1198
#define IDC_DRIVECOMBO                  1198
#define IDC_SPEEDCOMBO                  1199
#define IDC_SPEEDSTATIC                 1200
#define IDC_FILESBUTTON                 1201
#define IDC_YESBUTTON                   1202
#define IDC_NOBUTTON                    1203
#define IDC_BUTTON2                     1204
#define IDC_NOALLBUTTON                 1204
#define IDC_REPLACEINFOSTATIC           1206
#define IDC_OLDSIZESTATIC               1207
#define IDC_OLDDATESTATIC               1208
#define IDC_REPLACEINFO2STATIC          1209
#define IDC_REFRESHBUTTON               1209
#define IDC_NEWSIZESTATIC               1210
#define IDC_FILESYSSTATIC               1210
#define IDC_NEWDATESTATIC               1211
#define IDC_FILESYSCOMBO                1211
#define IDC_VERSIONCOMBO                1212
#define IDC_PARTACCESSSTATIC            1214
#define IDC_ASSOCIATEDISCIMAGECHECK     1215
#define IDC_DATACDBUTTON                1220
#define IDC_DATADVDBUTTON               1221
#define IDC_IDC_WHITESTATIC             1223
#define IDC_WIZARDCHECK                 1224
#define IDC_BUTTON3                     1225
#define IDC_NUMCOPIESSTATIC             1226
#define IDC_NUMCOPIESCOMBO              1228
#define IDC_PROJECTTREEVIEW             10001
#define IDC_PROJECTLISTVIEW             10002
#define IDC_SHELLTREEVIEW               10003
#define IDC_SHELLLISTVIEW               10004
#define IDC_TBCUSTOMIZE_TEXTCOMBO       10005
#define IDC_TBCUSTOMIZE_ICONCOMBO       10006
#define ID_MENUROOT_FILE                11001
#define ID_MENUROOT_EDIT                11002
#define ID_MENUROOT_ACTIONS             11003
#define ID_MENUROOT_VIEW                11004
#define ID_MENUROOT_OPTIONS             11005
#define ID_MENUROOT_HELP                11006
#define ID_ACTIONS_ERASERE              32772
#define ID_ACTIONS_EJECT                32773
#define ID_EJECTDISC_                   32776
#define ID_VIEW_PROGRAMLOG              32778
#define ID_ACTIONS_BURNIMAGE            32780
#define ID_OPTIONS_CONFIGURATION        32781
#define ID_OPTIONS_DEVICES              32782
#define ID_FILE_NEWPROJECT              32783
#define ID_NEWPROJECT_DATACD            32784
#define ID_NEWPROJECT_AUDIO             32785
#define ID_NEWPROJECT_MIXED             32786
#define ID_EDIT_NEWFOLDER               32787
#define ID_Menu                         32788
#define ID_EDIT_RENAME                  32790
#define ID_EDIT_REMOVE                  32791
#define ID_VIEW_LARGEICONS              32792
#define ID_VIEW_SMALLICONS              32793
#define ID_VIEW_LIST                    32794
#define ID_VIEW_DETAILS                 32795
#define ID_ACTIONS_BURNCOMPILATION      32800
#define ID_FILE_PROJECTPROPERTIES       32801
#define ID_BURNCOMPILATION_DISCIMAGE    32804
#define ID_BURNCOMPILATION_COMPACTDISC  32805
#define ID_ACTIONS_FIXATEDISC           32806
#define ID_ACTIONS_MANAGETRACKS         32807
#define ID_ACTIONS_COPYDISC             32808
#define ID_COPYDISC_COMPACTDISC         32811
#define ID_COPYDISC_DISCIMAGE           32812
#define ID_EDIT_ADDPROJECT              32814
#define ID_ADD_SELECTED                 32818
#define ID_ADD_ALL                      32819
#define ID_ACTIONS_DISCINFORMATION      32821
#define ID_ACTIONS_IMPORTSESSION        32822
#define ID_DISCINFORMATION_             32823
#define ID_HELP_HELPTOPICS              32824
#define ID_NEWPROJECT_DVDVIDEO          32826
#define ID_NEWPROJECT_DATADVD           32827
#define ID__DEVICESCAN                  32828
#define ID__DIAGNOSTICS_DEVICESCAN      32829
#define ID_DIAGNOSTICS_DEVICESCAN       32830
#define ID_VIEW_TOOLBARS                32831
#define ID_TOOLBARS_STANDARDBUTTONS     32832
#define ID_TOOLBARS_CUSTOMIZE           32833
#define ID_VIEW_STANDARDTOOLBAR         32834
#define ID_VIEW_TBCUSTOMIZE             32835
#define ID_EDIT_SELECTALL               32836
#define ID_EDIT_INVERTSELECTION         32837
#define ID_POPUPMENU_PROPERTIES         32840
#define ID_NEWPROJECT_DATACD32841       32841
#define ID_NEWPROJECT_DATACDMS          32842
#define ID_EDIT_IMPORT                  32843

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        297
#define _APS_NEXT_COMMAND_VALUE         32844
#define _APS_NEXT_CONTROL_VALUE         1229
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
